name: Code Coverage
description: Creates and uploads a code coverage report

inputs:
  codecov_token:
    type: string
    description: The Codecov token to use
    required: true

runs:
  using: composite
  steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: 0.15.0
          args: -- --test-threads 1

      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ inputs.codecov_token }}

      - uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
